### ISSUE TITLE
how to configure static files path? 

### ISSUE THREAD

**Issue by zzm88** [patrick330602/eagle-local-media-host#1]
images are located under "C:\Program Files\JetBrains\PyCharm 2021.3.3\jbr\bin\static\"
I am using PyCharm and I don't know why it use this path as default. I copied all the folders to the static folder under this project then it works.
How can I set the static file path?

**Comment by patrick330602** [comment]
I am not really sure. I develop this in VSCode on Mac so I am not sure how to change it. But I will possibly modify the path ion the project.

**Comment by patrick330602** [comment]
Currently made a new change that could possibly solve your problem

**Comment by zzm88** [comment]
Thank you! It works.
